# Dockerfile.sui
FROM rust:1.82-bookworm AS sui-builder

RUN curl -sSfL https://raw.githubusercontent.com/Mystenlabs/suiup/main/install.sh | sh

ENV PATH="/root/.local/bin:$PATH"

RUN suiup install sui@mainnet-1.57.3 -y

FROM debian:bookworm-slim
COPY --from=sui-builder /root/.local/bin/sui /usr/local/bin/sui